apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-rb
data:
  gitlab.rb: |
    external_url "https://gitlab"

    letsencrypt['enable'] = false
    mattermost['enable'] = false
    prometheus['enable'] = false
    grafana['enable'] = false

    gitlab_rails['initial_root_password'] = 'iNHGh9m/lN8KpBMMcDVWzANGzkVuXFMhzz/Ixi2osVw='

    nginx['ssl_certificate'] = "/etc/gitlab/cert/gitlab.crt"
    nginx['ssl_certificate_key'] = "/etc/gitlab/cert/gitlab.key"
    nginx['custom_gitlab_server_config'] = "listen 80;"
    nginx['listen_https'] = true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-ssl-script
data:
  ssl.sh: |
    set -x
    export CRTF="/cert"
    export KEY="$CRTF/ca.key"
    export KEYS="$CRTF/gitlab.key"
    export CRT="$CRTF/ca.crt"
    export CRTS="$CRTF/gitlab.crt"
    export CSR="$CRTF/gitlab.csr"

    openssl genrsa -out $KEY 2048
    openssl req -new -x509 -days 365 -key $KEY -subj "/C=CN/ST=GD/L=SZ/O=Acme, Inc./CN=Acme Root CA" -out $CRT
    #"/C=CN/ST=GD/L=SZ/O=Acme, Inc./CN=gitlab"
    openssl req -newkey rsa:2048 -nodes -keyout $KEYS -subj "/C=CN/ST=GD/L=SZ/O=Acme, Inc." -out $CSR --addext "subjectAltName = DNS:gitlab"

    openssl x509 -req -days 365 -in $CSR -CA $CRT -CAkey $KEY -CAcreateserial -out $CRTS
