apiVersion: apps/v1
kind: Deployment
metadata:
    name: gitlab
    labels:
      app: gitlab
spec:
    replicas: 1
    selector:
        matchLabels:
            app: gitlab
    template:
        metadata:
            labels:
                app: gitlab
        spec:
            hostname: gitlab
            volumes:
                - name: gitlabcers
                  hostPath:
                    path: /disk1/gitlab/certs
                - name: gitlabhome
                  hostPath:
                    path: /disk1/gitlab/
                - name: gitlab-rb
                  configMap:
                    name: gitlab-rb
            containers:
                - name: gitlab
                  image: gitlab/gitlab-ee:latest
                  tty: true
                  stdin: true
                  env:
                    - name: GITLAB_HOME
                      value: /srv/gitlab
                    - name: GITLAB_OMNIBUS_CONFIG
                      value: |
                        registry_external_url 'https://gitlab:9445'
                        nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab.local.p.crt"
                        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab.local.p.key"
                        registry_nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab.local.p.crt"
                        registry_nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab.local.p.key"
                  volumeMounts:
                    - mountPath: /etc/gitlab/ssl
                      name: gitlabcert
                    - mountPath: /srv/gitlab/
                      name: gitlabhome
                  ports:
                     - containerPort: 80
                     - containerPort: 22
                     - containerPort: 443
