apiVersion: apps/v1
kind: Deployment
metadata:
    name: DevOps
    labels:
      app: DevOps
spec:
    replicas: 1
    selector:
        matchLabels:
            app: DevOps
    template:
        metadata:
            labels:
                app: DevOps
        spec:
            hostname: gitlab.internal.home
            volumes:
                - name: gitlabhome
                  hostPath:
                    path: /disk1/gitlab/cert
                - name: gitlab-rb
                  configMap:
                    name: gitlab-rb
            containers:
                - name: gitlab
                  image: gitlab/gitlab-ee:latest
                  tty: true
                  stdin: true
                  volumeMounts:
                    - mountPath: /etc/gitlab/ssl
                      name: gitlabhome
                    - name: gitlab-rb
                      mountPath: "/srv/gitlab/config/gitlab.rb"
                      subPath: gitlab.rb
                      readOnly: true
                  ports:
                     - containerPort: 80
                     - containerPort: 22
                     - containerPort: 443
