apiVersion: apps/v1
kind: Deployment
metadata:
    name: DevOps
    labels:
      app: DevOps
spec:
    replicas: 1
    selector:
        matchLabels:
            app: DevOps
    template:
        metadata:
            labels:
                app: DevOps
        spec:
            volumes:
                - name: gitlabhome
                  hostPath:
                    path: /disk1/gitlab
            containers:
                - name: gitlab
                  hostname: gilab.internal.home
                  image: gitlab/gitlab-ee:latest
                  tty: true
                  stdin: true
                  env:
                    - name: GITLAB_HOME
                      value: /srv/gitlab
                  volumeMounts:
                    - mountPath: /srv/gitlab
                      name: gitlabhome
                  port:
                     - containerPort: 80
                     - containerPort: 22
                     - containerPort: 443
