apiVersion: apps/v1
kind: Deployment
metadata:
  name: gocd
  labels:
    app: gocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gocd
  template:
    metadata:
      labels:
        app: gocd
    spec:
      hostname: gocd
      hostAliases:
        - ip: 127.0.0.1
          hostnames:
            - gocd
      volumes:
        - name: gocd
          hostPath:
            type: DirectoryOrCreate
            path: /disk1/gocd/
        - name: gocdcert
          hostPath:
            type: DirectoryOrCreate
            path: /disk1/gitlab/cert
        - name: nginx-config
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: gitlab-ssl-script
          configMap:
            name: gitlab-ssl-script
            defaultMode: 0744
            items:
              - key: ssl.sh
                path: ssl.sh
      initContainers:
        - name: directory
          image: debian:latest
          volumeMounts:
            - mountPath: /godata
              name: gocd
          command:
            - chown
            - "-R"
            - "1000:1000"
            - "/godata"
        - name: openssl
          image: alpine/openssl
          volumeMounts:
            - mountPath: /cert
              name: gocdcert
            - mountPath: /ssl.sh
              name: gitlab-ssl-script
              subPath: ssl.sh
          command:
            - sh
            - /ssl.sh
            - gocd
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 3
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 3
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              name: nginx-config

        - name: gocd
          image: gocd/gocd-server:v22.3.0
          readinessProbe:
            tcpSocket:
              port: 8153
            initialDelaySeconds: 20
            periodSeconds: 3
          livenessProbe:
            tcpSocket:
              port: 8153
            initialDelaySeconds: 20
            periodSeconds: 3
          volumeMounts:
            - mountPath: /godata
              name: gocd
            - mountPath: /cert
              name: gocdcert
          ports:
            - containerPort: 8153
---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: gocd-agent
#   labels:
#     app: gocd-agent
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: gocd-agent
#   template:
#     metadata:
#       labels:
#         app: gocd-agent
#     spec:
#       hostname: gocd-agent
#       containers:
#         - name: agent
#           image: gocd/gocd-agent-debian-9:v22.1.0
#           args:
#             - "-sslVerificationMode"
#             - "NO_VERIFY_HOST"
#             - "-serverUrl"
#             - "https://gocd:8153"
