apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  volumes:
    - name: gitlabcert
      hostPath:
        type: DirectoryOrCreate
        path: /disk1/gitlab/cert
    - name: gitlabopt
      hostPath:
        type: DirectoryOrCreate
        path: /disk1/gitlab/gitlab
    - name: gitlabconf
      hostPath:
        type: DirectoryOrCreate
        path: /disk1/gitlab/gitlab-conf
    - name: gitlablog
      hostPath:
        type: DirectoryOrCreate
        path: /disk1/gitlab/gitlab-log
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
    - name: runner-config
      hostPath:
        path: /disk1/gitlab/runner
        type: DirectoryOrCreate
    - name: gocdssh
      hostPath:
        type: DirectoryOrCreate
        path: /disk1/gocd/ssh
    - name: gitlab-rb
      configMap:
        name: gitlab-rb
        items:
          - key: gitlab.rb
            path: gitlab.rb
    - name: gitlab-ssl-script
      configMap:
        name: gitlab-ssl-script
        defaultMode: 0744
        items:
          - key: ssl.sh
            path: ssl.sh
    - name: gocd
      hostPath:
        type: DirectoryOrCreate
        path: /disk1/gocd/
    - name: gocdcert
      hostPath:
        type: DirectoryOrCreate
        path: /disk1/gitlab/cert
    - name: nginx-config
      configMap:
        name: nginx-config
        items:
          - key: nginx.conf
            path: nginx.conf
    - name: cruise-config
      configMap:
        name: cruise-config
        items:
          - key: cruise-config.xml
            path: cruise-config.xml
  initContainers:
    #- name: openssl-ca
    #  image: alpine/openssl
    #  volumeMounts:
    #    - mountPath: /cert
    #      name: gitlabcert
    #    - mountPath: /ssl.sh
    #      name: gitlab-ssl-script
    #      subPath: ssl.sh
    #  command:
    #    - sh
    #    - /ssl.sh
    #    - CA
    - name: openssl-gitlab
      image: alpine/openssl
      volumeMounts:
        - mountPath: /cert
          name: gitlabcert
        - mountPath: /ssl.sh
          name: gitlab-ssl-script
          subPath: ssl.sh
      command:
        - sh
        - /ssl.sh
        - gitlab
    - name: openssl-gocd
      image: alpine/openssl
      volumeMounts:
        - mountPath: /cert
          name: gocdcert
        - mountPath: /ssl.sh
          name: gitlab-ssl-script
          subPath: ssl.sh
      command:
        - sh
        - /ssl.sh
        - gocd
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 443
      volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          name: nginx-config
        - mountPath: /cert
          name: gitlabcert
