---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
spec:
  type: ClusterIP #ClusterIP
  clusterIP: None
  selector:
    app: gitlab
  ports:
    - name: gitlab
      port: 8181
---
apiVersion: v1
kind: Service
metadata:
  name: gocd
spec:
  type: ClusterIP #ClusterIP
  clusterIP: None
  selector:
    app: gocd
  ports:
    - name: gocd
      port: 8153
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: ClusterIP #ClusterIP
  selector:
    app: nginx
  ports:
    - name: nignx
      port: 443
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-ssh
spec:
  type: ClusterIP
  selector:
    app: gitlab
  ports:
    - name: "ssh"
      protocol: TCP
      port: 9022
      targetPort: 22
