
apiVersion: v1
kind: Service
metadata:
  name: gitlab
spec:
  type: LoadBalancer
  selector:
    app: DevOps
  ports:
    - name: "https"
      protocol: TCP
      port: 9443
      targetPort: 443
    - name: "http"
      protocol: TCP
      port: 9080
      targetPort: 80
    - name: "ssh"
      protocol: TCP
      port: 9022
      targetPort: 22
