---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: gitlab
  ports:
    - name: gitlab
      port: 8181
---
apiVersion: v1
kind: Service
metadata:
  name: gocd
spec:
  type: ClusterIP #ClusterIP
  clusterIP: None
  selector:
    app: gocd
  ports:
    - name: gocd
      port: 8153
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: nginx
#spec:
#  type: ClusterIP #ClusterIP
#  selector:
#    app: nginx
#  ports:
#    - name: nignx
#      port: 443
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-ssh
spec:
  type: LoadBalancer
  selector:
    app: gitlab
  ports:
    - name: "ssh"
      protocol: TCP
      port: 9022
      targetPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: teamcity
spec:
  type: ClusterIP
  selector:
    app: teamcity
  ports:
    - name: "web"
      protocol: TCP
      port: 8111
      targetPort: 8111
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlab-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: "gitlab.in.cluster.local"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitlab
                port:
                  number: 8181
