
apiVersion: v1
kind: Service
metadata:
  name: gitlab
spec:
  type: LoadBalancer
  selector:
    app: DevOps
  ports:
    - name: "https"
      protocol: TCP
      port: 8443
      targetPort: 443
---
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: devops-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: gitlab.internal.home
    http:
      paths:
      - path: /
        backend:
          serviceName: gitlab
          servicePort: 443
