---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-http
spec:
  type: LoadBalancer #ClusterIP
  selector:
    app: gitlab
  ports:
    - name: "https"
      port: 9443
      targetPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-ssh
spec:
  type: LoadBalancer
  selector:
    app: gitlab
  ports:
    - name: "ssh"
      protocol: TCP
      port: 9022
      targetPort: 22
