apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  #- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - ingress.yaml
  #- https://github.com/argoproj/argo-workflows/releases/download/v3.4.4/install.yaml
  #- https://raw.githubusercontent.com/argoproj/argo-events/stable/manifests/install.yaml
  #- https://raw.githubusercontent.com/argoproj/argo-events/stable/manifests/install-validating-webhook.yaml
  #- https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/eventbus/native.yaml
