concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "runner01"
  url = "http://gitlab"
  id = 1
  token = ""
  token_obtained_at = 2022-12-07T13:46:11Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  clone_url = "https://gitlab:9443"
  pre_clone_script = '''
  echo " gitlab" >> /etc/hosts
  cp /cert/ca.crt /etc/ssl/certs
  update-ca-certificates
  git config --global http.sslVerify false
  '''

  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "debian:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache","/disk1/gitlab/cert:/cert"]
    shm_size = 0
